<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerThK7U11\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerThK7U11/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerThK7U11.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerThK7U11\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerThK7U11\App_KernelDevDebugContainer([
    'container.build_hash' => 'ThK7U11',
    'container.build_id' => '4a3d83da',
    'container.build_time' => 1593187486,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerThK7U11');
