<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHr3iUj8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHr3iUj8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHr3iUj8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHr3iUj8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHr3iUj8\App_KernelDevDebugContainer([
    'container.build_hash' => 'Hr3iUj8',
    'container.build_id' => '5343b1c5',
    'container.build_time' => 1593080632,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHr3iUj8');
