<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIgoUdAZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIgoUdAZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIgoUdAZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIgoUdAZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIgoUdAZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'IgoUdAZ',
    'container.build_id' => '870ecc08',
    'container.build_time' => 1592993711,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIgoUdAZ');
